version: '3.3'

services: 
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
    #  - "80:80"
     # - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sim:
    image: moa_info:latest
    labels: 
      - "traefik.frontend.rule=Host:sim.docker.localhost"
